Run actions/deploy-pages@v2
  
Artifact exchange URL: https://pipelinesghubeus7.actions.githubusercontent.com/nVYPfQ46MHmX10vrCRYdexjLlXvj0ehIIwps4sKKnqwCUwP61A/_apis/pipelines/workflows/6275405289/artifacts?api-version=6.0-preview
Creating Pages deployment with payload:
{
	"artifact_url": "https://pipelinesghubeus7.actions.githubusercontent.com/nVYPfQ46MHmX10vrCRYdexjLlXvj0ehIIwps4sKKnqwCUwP61A/_apis/pipelines/1/runs/26/artifacts?artifactName=github-pages&%24expand=SignedContent",
	"pages_build_version": "f43d43acc9f66a2f4f5e2463c67270b8f0f04c6a",
	"oidc_token": "***"
}
Error: Creating Pages deployment failed
Error: HttpError: Invalid artifact url
    at /home/runner/work/_actions/actions/deploy-pages/v2/webpack:/deploy-pages/node_modules/@octokit/request/dist-node/index.js:86:1
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at createPagesDeployment (/home/runner/work/_actions/actions/deploy-pages/v2/webpack:/deploy-pages/src/internal/api-client.js:126:1)
    at Deployment.create (/home/runner/work/_actions/actions/deploy-pages/v2/webpack:/deploy-pages/src/internal/deployment.js:80:1)
    at main (/home/runner/work/_actions/actions/deploy-pages/v2/webpack:/deploy-pages/src/index.js:30:1)
Error: Error: Failed to create deployment (status: 400) with build version f43d43acc9f66a2f4f5e[24](https://github.com/GlobalMin/jameson-resume/actions/runs/6275405289/job/17042818285#step:8:25)63c67[27](https://github.com/GlobalMin/jameson-resume/actions/runs/6275405289/job/17042818285#step:8:28)0b8f0f04c6a. Responded with: Invalid artifact url
